name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at 00:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: Mohamed0sman
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
